language: node_js

node_js:
  - "10.15.0"

notifications:
  slack:
    rooms:
      - ${GENERAL_ROOM}
      - ${KIT_ROOM}

sudo: required

addons:
  artifacts: true

cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - google-chrome-stable

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3


before_script:
  - "npm install"
  - "npm install -g reg-suit"
  - npm start &


script:
  - npm run e2e
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*" # This line is necessary to disable --single-branch option to fetch all remote branches on TravisCI.
  - git fetch origin
  - git checkout $TRAVIS_BRANCH || git checkout -b $TRAVIS_BRANCH
  - reg-suit run --config ./regconfig.json
